# Generated by Django 4.2.2 on 2023-06-16 22:10

import django.core.validators
from django.db import migrations, models
import django_plant.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(default='d', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(default='url', verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.CharField(default='name', max_length=20, validators=[django.core.validators.MinLengthValidator(2), django_plant.web.validators.plant_name_validator], verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], default='Indoor Plants', max_length=14, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='name', max_length=20, validators=[django_plant.web.validators.profile_name_validator], verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='name', max_length=20, validators=[django_plant.web.validators.profile_name_validator], verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='name', max_length=10, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
    ]
